### ISSUE TITLE
Could not update to v2.0.1 in Xamarin.Forms PCL application

### ISSUE THREAD

**Issue by robertger** [1iveowl/HttpMachine.PCL#2]
I used your library on a Xamarin.Forms PCL project which is targeting Android, iOS and UWP.
While trying to update from v1.1.1 to v2.0.1 of your library, I got the following error:

Could not install package 'HttpMachine.PCL 2.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework.

Is there something I can do or is the problem related to your updated NuGet package?

**Comment by 1iveowl** [comment]
Thank you for your comment. 

That is correct. I move from Profile7 to .NET Standard 1.4 

Here is a good blog post on this topic: [.NET Standard Library with Xamarin Forms](https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/)

Now, you have at least two choices. You can either continue to use version 1.1.1. or you can update your library to .NET Stanard 1.4.

There are no difference besides the update of the library format at this point in time.

**Comment by robertger** [comment]
I had a look at the mentioned blog post. It sounds good and I think I would give the .NET  Standard Library a try.
If it didn’t work for me now I could stay at the profile based PCL until we have a broader support for the new standard  library.
Thanks a lot for your quick help :-)
